name: Python Package Build and Install (Pip) Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Build Package (Pip)
      run: |
        pip install build
        python -m build
    - name: Install Package (Pip)
      run: |
        pip install dist/*.whl
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
    - name: Uninstall Package (Pip)
      run: |
        pip uninstall BOSolver
